# Generated by Django 4.0.1 on 2022-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('cash_value', models.FloatField()),
                ('date', models.DateField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
