# Generated by Django 4.0.1 on 2022-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_deposito_delete_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
